import { Router } from "express";
import { z } from "zod";
import PDFDocument from "pdfkit";
import { prisma } from "../lib/prisma.js";
import { requireAuth, requirePermission, type AuthedRequest } from "../middleware/auth.js";
import { recordAudit } from "../lib/audit.js";
import { encryptNumber, decryptNumber } from "../lib/crypto.js";

// Proforma Invoice (Round-4 operational-flow addendum, item 5): a
// preliminary, non-statutory document generated by this system itself
// (unlike the actual Tally tax invoice, which InvoiceReference only holds
// a reference to) — own numbering series so it never collides with a real
// invoice number, no tax breakup, bank details for advance payment.
// Owner + Accountant only, consistent with every other pricing-bearing
// document in the system.
export const proformaInvoicesRouter = Router();

proformaInvoicesRouter.use(requireAuth, requirePermission("pricing.managePI"));

function serializeLine<T extends { unitPrice: string }>(line: T) {
  return { ...line, unitPrice: decryptNumber(line.unitPrice) };
}

function serialize<T extends { lines: any[] }>(pi: T) {
  return { ...pi, lines: pi.lines.map(serializeLine) };
}

async function nextPiNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `PI-${year}-`;
  const count = await prisma.proformaInvoice.count({ where: { piNumber: { startsWith: prefix } } });
  return `${prefix}${String(count + 1).padStart(4, "0")}`;
}

proformaInvoicesRouter.get("/order/:orderId", async (req, res) => {
  const pis = await prisma.proformaInvoice.findMany({
    where: { orderId: req.params.orderId },
    include: { lines: { include: { sku: true } }, createdBy: { select: { id: true, name: true } } },
    orderBy: { version: "desc" },
  });
  res.json(pis.map(serialize));
});

const createSchema = z.object({
  orderId: z.string().min(1),
  validUntil: z.string().datetime(),
  lines: z
    .array(z.object({ skuId: z.string().min(1), qty: z.number().int().positive(), unit: z.string().min(1), unitPrice: z.number().nonnegative() }))
    .min(1),
});

// Creates a new PI for the order. If an ACTIVE one already exists, it's a
// reissue: the previous version is marked SUPERSEDED and the new one gets
// version+1 — never mutates a previously issued PI's content, so an
// earlier printed copy always matches what this system says it said.
proformaInvoicesRouter.post("/", async (req: AuthedRequest, res) => {
  const parsed = createSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "Invalid request body", details: parsed.error.flatten() });

  const order = await prisma.order.findUnique({ where: { id: parsed.data.orderId } });
  if (!order) return res.status(404).json({ error: "Order not found" });

  const previousActive = await prisma.proformaInvoice.findFirst({ where: { orderId: order.id, status: "ACTIVE" } });

  const piNumber = await nextPiNumber();
  const pi = await prisma.$transaction(async (tx) => {
    if (previousActive) {
      await tx.proformaInvoice.update({ where: { id: previousActive.id }, data: { status: "SUPERSEDED" } });
    }
    return tx.proformaInvoice.create({
      data: {
        piNumber,
        orderId: order.id,
        version: (previousActive?.version ?? 0) + 1,
        validUntil: new Date(parsed.data.validUntil),
        createdById: req.user!.id,
        lines: {
          create: parsed.data.lines.map((l) => ({ skuId: l.skuId, qty: l.qty, unit: l.unit, unitPrice: encryptNumber(l.unitPrice) })),
        },
      },
      include: { lines: { include: { sku: true } }, createdBy: { select: { id: true, name: true } } },
    });
  });

  await recordAudit({
    userId: req.user!.id,
    action: previousActive ? "REISSUE" : "CREATE",
    entityType: "ProformaInvoice",
    entityId: pi.id,
    after: { piNumber: pi.piNumber, orderId: order.id, version: pi.version, supersedes: previousActive?.piNumber ?? null },
  });

  res.status(201).json(serialize(pi));
});

proformaInvoicesRouter.get("/:id", async (req, res) => {
  const pi = await prisma.proformaInvoice.findUnique({
    where: { id: req.params.id },
    include: { lines: { include: { sku: true } }, order: true, createdBy: { select: { id: true, name: true } } },
  });
  if (!pi) return res.status(404).json({ error: "Proforma invoice not found" });
  res.json(serialize(pi));
});

// Renders the actual PDF document — the deliverable, not just a reference
// to one, since a PI (unlike the Tally tax invoice) isn't generated
// externally.
proformaInvoicesRouter.get("/:id/pdf", async (req, res) => {
  const pi = await prisma.proformaInvoice.findUnique({
    where: { id: req.params.id },
    include: { lines: { include: { sku: true } }, order: true },
  });
  if (!pi) return res.status(404).json({ error: "Proforma invoice not found" });
  const settings = await prisma.companySettings.findUnique({ where: { id: "singleton" } });

  res.type("application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${pi.piNumber}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text("PROFORMA INVOICE", { align: "center" });
  if (pi.status === "SUPERSEDED") {
    doc.fontSize(10).fillColor("red").text("SUPERSEDED — see the latest version for this order", { align: "center" }).fillColor("black");
  }
  doc.moveDown();

  doc.fontSize(11);
  doc.text(`PI Number: ${pi.piNumber}  (version ${pi.version})`);
  doc.text(`Date: ${pi.issueDate.toLocaleDateString()}`);
  doc.text(`Valid until: ${pi.validUntil.toLocaleDateString()}`);
  doc.text(`Order reference: ${pi.order.orderNumber}`);
  doc.moveDown();

  doc.text(`Buyer: ${pi.order.buyerName}`);
  if (pi.order.buyerContact) doc.text(`Contact: ${pi.order.buyerContact}`);
  doc.moveDown();

  const tableTop = doc.y;
  const cols = { name: 50, qty: 260, unit: 320, price: 380, amount: 460 };
  doc.font("Helvetica-Bold");
  doc.text("Item", cols.name, tableTop);
  doc.text("Qty", cols.qty, tableTop);
  doc.text("Unit", cols.unit, tableTop);
  doc.text("Price", cols.price, tableTop);
  doc.text("Amount", cols.amount, tableTop);
  doc.font("Helvetica");
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.3);

  let subtotal = 0;
  for (const line of pi.lines) {
    const price = decryptNumber(line.unitPrice);
    const amount = price * line.qty;
    subtotal += amount;
    const y = doc.y;
    // SKU name, per the buyer-facing document requirement — never the
    // internal code, which buyers won't recognize.
    doc.text(line.sku.name, cols.name, y, { width: 200 });
    doc.text(String(line.qty), cols.qty, y);
    doc.text(line.unit, cols.unit, y);
    doc.text(price.toFixed(2), cols.price, y);
    doc.text(amount.toFixed(2), cols.amount, y);
    doc.moveDown();
  }

  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);
  doc.font("Helvetica-Bold");
  doc.text(`Subtotal: ${subtotal.toFixed(2)}`, { align: "right" });
  doc.text(`Total: ${subtotal.toFixed(2)}`, { align: "right" });
  doc.font("Helvetica");
  doc.moveDown();

  // No GST/tax breakup — this is deliberately not the statutory tax
  // document (see the addendum, item 5).
  doc.fontSize(9).fillColor("gray");
  doc.text("Excludes applicable taxes — final amount will be confirmed on the tax invoice.");
  doc.fillColor("black").fontSize(11);
  doc.moveDown();

  if (settings?.bankAccountName || settings?.bankAccountNumber) {
    doc.font("Helvetica-Bold").text("Bank details for advance payment").font("Helvetica");
    if (settings.bankAccountName) doc.text(`Account name: ${settings.bankAccountName}`);
    if (settings.bankAccountNumber) doc.text(`Account number: ${settings.bankAccountNumber}`);
    if (settings.bankIfsc) doc.text(`IFSC: ${settings.bankIfsc}`);
    if (settings.bankName) doc.text(`Bank: ${settings.bankName}`);
    doc.moveDown();
  }

  doc.fontSize(9).fillColor("gray");
  doc.text(
    `This is a Proforma Invoice, valid until ${pi.validUntil.toLocaleDateString()}. It is not a tax invoice and does not itself trigger dispatch or billing.`
  );

  doc.end();
});
