import { Router } from "express";
import { z } from "zod";
import PDFDocument from "pdfkit";
import { prisma } from "../lib/prisma.js";
import { requireAuth, requirePermission, type AuthedRequest } from "../middleware/auth.js";
import { recordAudit } from "../lib/audit.js";
import { encryptNumber, decryptNumber } from "../lib/crypto.js";

// Proforma Invoice (Round-4 operational-flow addendum, item 5): a
// preliminary, non-statutory document generated by this system itself
// (unlike the actual Tally tax invoice, which InvoiceReference only holds
// a reference to) — own numbering series so it never collides with a real
// invoice number, no tax breakup, bank details for advance payment.
// Owner + Accountant only, consistent with every other pricing-bearing
// document in the system.
export const proformaInvoicesRouter = Router();

proformaInvoicesRouter.use(requireAuth, requirePermission("pricing.managePI"));

function serializeLine<T extends { unitPrice: string }>(line: T) {
  return { ...line, unitPrice: decryptNumber(line.unitPrice) };
}

function serialize<T extends { lines: any[] }>(pi: T) {
  return { ...pi, lines: pi.lines.map(serializeLine) };
}

async function nextPiNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `PI-${year}-`;
  const count = await prisma.proformaInvoice.count({ where: { piNumber: { startsWith: prefix } } });
  return `${prefix}${String(count + 1).padStart(4, "0")}`;
}

proformaInvoicesRouter.get("/order/:orderId", async (req, res) => {
  const pis = await prisma.proformaInvoice.findMany({
    where: { orderId: req.params.orderId },
    include: { lines: { include: { sku: true } }, createdBy: { select: { id: true, name: true } } },
    orderBy: { version: "desc" },
  });
  res.json(pis.map(serialize));
});

const createSchema = z.object({
  orderId: z.string().min(1),
  validUntil: z.string().datetime(),
  lines: z
    .array(z.object({ skuId: z.string().min(1), qty: z.number().int().positive(), unit: z.string().min(1), unitPrice: z.number().nonnegative() }))
    .min(1),
});

// Creates a new PI for the order. If an ACTIVE one already exists, it's a
// reissue: the previous version is marked SUPERSEDED and the new one gets
// version+1 — never mutates a previously issued PI's content, so an
// earlier printed copy always matches what this system says it said.
proformaInvoicesRouter.post("/", async (req: AuthedRequest, res) => {
  const parsed = createSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "Invalid request body", details: parsed.error.flatten() });

  const order = await prisma.order.findUnique({ where: { id: parsed.data.orderId } });
  if (!order) return res.status(404).json({ error: "Order not found" });

  const previousActive = await prisma.proformaInvoice.findFirst({ where: { orderId: order.id, status: "ACTIVE" } });

  const piNumber = await nextPiNumber();
  const pi = await prisma.$transaction(async (tx) => {
    if (previousActive) {
      await tx.proformaInvoice.update({ where: { id: previousActive.id }, data: { status: "SUPERSEDED" } });
    }
    return tx.proformaInvoice.create({
      data: {
        piNumber,
        orderId: order.id,
        version: (previousActive?.version ?? 0) + 1,
        validUntil: new Date(parsed.data.validUntil),
        createdById: req.user!.id,
        lines: {
          create: parsed.data.lines.map((l) => ({ skuId: l.skuId, qty: l.qty, unit: l.unit, unitPrice: encryptNumber(l.unitPrice) })),
        },
      },
      include: { lines: { include: { sku: true } }, createdBy: { select: { id: true, name: true } } },
    });
  });

  await recordAudit({
    userId: req.user!.id,
    action: previousActive ? "REISSUE" : "CREATE",
    entityType: "ProformaInvoice",
    entityId: pi.id,
    after: { piNumber: pi.piNumber, orderId: order.id, version: pi.version, supersedes: previousActive?.piNumber ?? null },
  });

  res.status(201).json(serialize(pi));
});

proformaInvoicesRouter.get("/:id", async (req, res) => {
  const pi = await prisma.proformaInvoice.findUnique({
    where: { id: req.params.id },
    include: { lines: { include: { sku: true } }, order: true, createdBy: { select: { id: true, name: true } } },
  });
  if (!pi) return res.status(404).json({ error: "Proforma invoice not found" });
  res.json(serialize(pi));
});

// Renders the actual PDF document — the deliverable, not just a reference
// to one, since a PI (unlike the Tally tax invoice) isn't generated
// externally.
proformaInvoicesRouter.get("/:id/pdf", async (req, res) => {
  const pi = await prisma.proformaInvoice.findUnique({
    where: { id: req.params.id },
    include: { lines: { include: { sku: true } }, order: true },
  });
  if (!pi) return res.status(404).json({ error: "Proforma invoice not found" });
  const settings = await prisma.companySettings.findUnique({ where: { id: "singleton" } });

  res.type("application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${pi.piNumber}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text("PROFORMA INVOICE", { align: "center" });
  if (pi.status === "SUPERSEDED") {
    doc.fontSize(10).fillColor("red").text("SUPERSEDED — see the latest version for this order", { align: "center" }).fillColor("black");
  }
  doc.moveDown();

  doc.fontSize(11);
  doc.text(`PI Number: ${pi.piNumber}  (version ${pi.version})`);
  doc.text(`Date: ${pi.issueDate.toLocaleDateString()}`);
  doc.text(`Valid until: ${pi.validUntil.toLocaleDateString()}`);
  doc.text(`Order reference: ${pi.order.orderNumber}`);
  doc.moveDown();

  doc.text(`Buyer: ${pi.order.buyerName}`);
  if (pi.order.buyerContact) doc.text(`Contact: ${pi.order.buyerContact}`);
  doc.moveDown();

  // --- Item table ---------------------------------------------------
  // Dark navy header (bold/uppercase/white, letter-spaced), alternating
  // row shading, right-aligned numerals for Qty/Rate/Amount, bold item
  // names, thin row separators distinct from the header itself.
  const TABLE_X = 50;
  const TABLE_WIDTH = 495; // page width (595) - 2x50 margin
  const NAVY = "#1a1f2b";
  const ROW_SHADE = "#f8f9fb";
  const BORDER = "#e2e4e9";
  const CELL_PAD_X = 10;
  const CELL_PAD_Y = 7;
  const ROW_FONT_SIZE = 10;

  const colName = { x: TABLE_X + CELL_PAD_X, width: 200 };
  const colQty = { x: 270, width: 50 };
  const colUnit = { x: 325, width: 55 };
  const colRate = { x: 385, width: 75 };
  const colAmount = { x: 465, width: TABLE_X + TABLE_WIDTH - CELL_PAD_X - 465 };

  let tableY = doc.y;
  const headerHeight = ROW_FONT_SIZE + CELL_PAD_Y * 2;
  doc.rect(TABLE_X, tableY, TABLE_WIDTH, headerHeight).fill(NAVY);
  doc
    .fillColor("white")
    .font("Helvetica-Bold")
    .fontSize(9);
  const headerTextY = tableY + CELL_PAD_Y;
  const headerOpts = { characterSpacing: 0.5 };
  doc.text("ITEM", colName.x, headerTextY, headerOpts);
  doc.text("QTY", colQty.x, headerTextY, { ...headerOpts, width: colQty.width, align: "right" });
  doc.text("UNIT", colUnit.x, headerTextY, { ...headerOpts, width: colUnit.width });
  doc.text("RATE", colRate.x, headerTextY, { ...headerOpts, width: colRate.width, align: "right" });
  doc.text("AMOUNT", colAmount.x, headerTextY, { ...headerOpts, width: colAmount.width, align: "right" });
  doc.fillColor("black").font("Helvetica").fontSize(ROW_FONT_SIZE);
  tableY += headerHeight;

  let subtotal = 0;
  pi.lines.forEach((line, i) => {
    const price = decryptNumber(line.unitPrice);
    const amount = price * line.qty;
    subtotal += amount;

    // SKU name, per the buyer-facing document requirement — never the
    // internal code, which buyers won't recognize.
    doc.font("Helvetica-Bold").fontSize(ROW_FONT_SIZE);
    const nameHeight = doc.heightOfString(line.sku.name, { width: colName.width });
    const rowHeight = Math.max(ROW_FONT_SIZE + CELL_PAD_Y * 2, nameHeight + CELL_PAD_Y * 2);

    // Even rows (2nd, 4th, ...) get the light shade; odd rows stay white.
    if (i % 2 === 1) {
      doc.rect(TABLE_X, tableY, TABLE_WIDTH, rowHeight).fill(ROW_SHADE);
    }

    const textY = tableY + CELL_PAD_Y;
    doc.fillColor("black").font("Helvetica-Bold").text(line.sku.name, colName.x, textY, { width: colName.width });
    doc.font("Helvetica");
    doc.text(String(line.qty), colQty.x, textY, { width: colQty.width, align: "right" });
    doc.text(line.unit, colUnit.x, textY, { width: colUnit.width });
    doc.text(price.toFixed(2), colRate.x, textY, { width: colRate.width, align: "right" });
    doc.text(amount.toFixed(2), colAmount.x, textY, { width: colAmount.width, align: "right" });

    doc
      .moveTo(TABLE_X, tableY + rowHeight)
      .lineTo(TABLE_X + TABLE_WIDTH, tableY + rowHeight)
      .strokeColor(BORDER)
      .lineWidth(0.5)
      .stroke()
      .strokeColor("black")
      .lineWidth(1);

    tableY += rowHeight;
  });

  doc.y = tableY + 10;
  doc.font("Helvetica-Bold").fontSize(11);
  doc.text(`Subtotal: ${subtotal.toFixed(2)}`, { align: "right" });
  doc.text(`Total: ${subtotal.toFixed(2)}`, { align: "right" });
  doc.font("Helvetica");
  doc.moveDown();

  // No GST/tax breakup — this is deliberately not the statutory tax
  // document (see the addendum, item 5).
  doc.fontSize(9).fillColor("gray");
  doc.text("Excludes applicable taxes — final amount will be confirmed on the tax invoice.");
  doc.fillColor("black").fontSize(11);
  doc.moveDown();

  if (settings?.bankAccountName || settings?.bankAccountNumber) {
    doc.font("Helvetica-Bold").text("Bank details for advance payment").font("Helvetica");
    if (settings.bankAccountName) doc.text(`Account name: ${settings.bankAccountName}`);
    if (settings.bankAccountNumber) doc.text(`Account number: ${settings.bankAccountNumber}`);
    if (settings.bankIfsc) doc.text(`IFSC: ${settings.bankIfsc}`);
    if (settings.bankName) doc.text(`Bank: ${settings.bankName}`);
    doc.moveDown();
  }

  doc.fontSize(9).fillColor("gray");
  doc.text(
    `This is a Proforma Invoice, valid until ${pi.validUntil.toLocaleDateString()}. It is not a tax invoice and does not itself trigger dispatch or billing.`
  );

  doc.end();
});
